// <auto-generated />
namespace Organizer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ToDoSharingPart2Migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ToDoSharingPart2Migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201706041557566_ToDoSharingPart2Migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
